export default {
  fontWeight: '400',
  cursor: 'pointer',
  textDecoration: 'underline',
  opacity: '1',
  textDecorationHover: 'underline',
  opacityHover: '0.8',
  colorDanger: 'inherit',
  colorWarning: 'inherit',
  colorSuccess: 'inherit',
  colorInfo: 'inherit',
  colorDangerDark: 'inherit',
  colorWarningDark: 'inherit',
  colorSuccessDark: 'inherit',
  colorInfoDark: 'inherit',
};
