export default {
  backgroundColor: 'rgba(0,0,0,0)',
  color: 'rgba(0,0,0,0.56)',
  textDecoration: 'none',
  textTransform: 'uppercase',
  cursor: 'pointer',
  colorFocus: '#0073e7',
  textDecorationFocus: 'underline',
  fontWeightFocus: '400',
  colorHover: '#0073e7',
  textDecorationHover: 'none',
  fontWeightHover: '400',
  colorActive: 'black',
  textDecorationActive: 'none',
  fontWeightActive: '700',
  backgroundColorDark: 'rgba(0,0,0,0)',
  colorDark: 'rgba(255,255,255,0.6)',
  colorFocusDark: '#00abf3',
  colorHoverDark: '#00abf3',
  colorActiveDark: 'white',
};
