export default {
  borderWidth: '2px',
  style: 'solid',
  color: 'white',
  border: '2px solid white',
  paddingLeft: '2px',
  paddingRight: '2px',
  width: '6px',
  shortLineLength: '3px',
  longLineLength: '6px',
  top: '5px',
  left: '4px',
  angle: '45deg',
  zIndex: '3',
  animationChecked: 'qtm-keyframes-drawCheck 0.32s',
  colorDisabled: 'white',
  colorDark: 'white',
  colorDisabledDark: 'rgba(255,255,255,0.2)',
};
