export default {
  color: '#0073e7',
  paddingLeft: '2px',
  paddingRight: '2px',
  paddingTop: '2px',
  paddingBottom: '2px',
  backgroundColorChecked: 'rgba(0,0,0,0)',
  borderColorChecked: 'black',
  colorDisabled: '#cececf',
  backgroundColorDisabled: 'rgba(0,0,0,0)',
  borderColorDisabled: '#cececf',
  colorDark: '#1f91ff',
  backgroundColorCheckedDark: 'rgba(0,0,0,0)',
  borderColorCheckedDark: '#dcdedf',
  colorDisabledDark: '#4d595f',
  backgroundColorDisabledDark: 'rgba(0,0,0,0)',
  borderColorDisabledDark: '#4d595f',
};
