export default {
  size: '14px',
  lineHeight: '16px',
  marginTop: '0',
  marginBottom: '4px',
  marginLeft: '0',
  paddingLeft: '0',
  top: '1px',
  left: '1px',
  borderRadius: '1px',
  borderColor: 'black',
  borderWidth: '2px',
  borderStyle: 'solid',
  border: '2px solid black',
  height: '10px',
  width: '14px',
  transition: 'border-color 0.1s ease-in-out',
  backgroundColor: 'rgba(0,0,0,0)',
  animationChecked: 'qtm-keyframes-colorAndWaterDrop 0.32s',
  paddingLeftRight: '22px',
  paddingTopInline: '0',
  paddingLeftInline: '16px',
  boxShadowFocus: 'none',
  borderColorFocus: 'black',
  backgroundColorFocus: 'rgba(0,115,231,0.15)',
  backgroundColorFocusChecked: '#0073e7',
  borderColorChecked: '#0073e7',
  borderChecked: '2px solid #0073e7',
  backgroundColorChecked: '#0073e7',
  borderColorHover: 'black',
  borderColorHoverChecked: '#0073e7',
  borderHover: '2px solid black',
  borderHoverChecked: '2px solid #0073e7',
  backgroundColorHover: 'rgba(0,115,231,0.15)',
  backgroundColorHoverChecked: '#0073e7',
  borderColorDisabled: '#cececf',
  borderDisabled: '2px solid #cececf',
  backgroundColorDisabled: 'rgba(0,0,0,0)',
  backgroundColorDisabledChecked: '#cececf',
  borderColorDark: '#dcdedf',
  backgroundColorDark: 'rgba(0,0,0,0)',
  boxShadowFocusDark: 'none',
  borderColorFocusDark: '#dcdedf',
  backgroundColorFocusDark: 'rgba(0,115,231,0.4)',
  backgroundColorFocusCheckedDark: '#1f91ff',
  borderColorCheckedDark: '#1f91ff',
  backgroundColorCheckedDark: '#1f91ff',
  borderColorHoverDark: 'white',
  borderColorHoverCheckedDark: '#1f91ff',
  backgroundColorHoverDark: 'rgba(0,115,231,0.4)',
  backgroundColorHoverCheckedDark: 'rgba(0,0,0,0)',
  borderColorDisabledDark: '#4d595f',
  backgroundColorDisabledDark: 'rgba(0,0,0,0)',
  backgroundColorDisabledCheckedDark: '#4d595f',
};
