export default {
 color: '#0073e7',
 borderWidth: '0',
 borderStyle: 'solid',
 borderColor: 'rgba(0,0,0,0)',
 border: 'none',
 fontFamily: 'QuantumIcons',
 fontWeight: '900',
 fontSize: '10px',
 icon: '',
 letterSpacing: 'normal',
 lineHeight: '10px',
 size: '14px',
 height: '14px',
 width: '14px',
 fontStyle: 'normal',
 top: '9px',
 right: '8px',
 backgroundColor: 'rgba(0,0,0,0)',
 paddingTop: '2px',
 paddingRight: '2px',
 paddingBottom: '2px',
 paddingLeft: '2px',
 paddingLeftXs: '4px',
 padding: '2px 2px 2px 2px',
 transition: 'transform 0.4s ease',
 colorHover: '#0073e7',
 backgroundColorHover: 'rgba(0,0,0,0)',
 colorActive: '#0073e7',
 backgroundColorActive: 'rgba(0,0,0,0)',
 transformActive: 'none',
 colorDisabled: '#cececf',
 backgroundColorDisabled: 'rgba(0,0,0,0)',
 borderColorDisabled: 'rgba(0,0,0,0)',
 colorDark: '#1f91ff',
 borderColorDark: 'rgba(0,0,0,0)',
 backgroundColorDark: 'rgba(0,0,0,0)',
 colorDarkHover: '#1f91ff',
 backgroundColorHoverDark: 'rgba(0,0,0,0)',
 colorDarkActive: '#1f91ff',
 backgroundColorDarkActive: 'rgba(0,0,0,0)',
 colorDisabledDark: '#4d595f',
 backgroundColorDisabledDark: 'rgba(0,0,0,0)',
 borderColorDisabledDark: 'rgba(0,0,0,0)'
};