export default {
  height: '32px',
  width: '100%',
  lineHeight: '16px',
  fontColor: 'black',
  fontSize: '16px',
  backgroundColor: 'rgba(0,0,0,0)',
  borderRadius: '0',
  borderStyle: 'solid',
  borderColor: 'rgba(101,102,104,0.64)',
  border: 'solid rgba(101,102,104,0.64)',
  borderWidthTop: '0',
  borderWidthRight: '0',
  borderWidthBottom: '1px',
  borderWidthLeft: '0',
  borderWidth: '0 0 1px 0',
  paddingTop: '7px',
  paddingRight: '24px',
  paddingRightClear: '56px',
  paddingBottom: '7px',
  paddingLeft: '0',
  padding: '7px 24px 7px 0',
  textAlign: 'left',
  cursor: 'pointer',
  boxShadow: 'none',
  borderColorFocus: '#0073e7',
  boxShadowFocus: 'none',
  borderColorHover: '#656668',
  borderColorError: '#e5004c',
  colorError: 'black',
  boxShadowErrorFocus: 'unset',
  borderColorWarning: '#ffc002',
  colorWarning: 'black',
  boxShadowWarningFocus: 'unset',
  colorDisabled: '#cececf',
  backgroundColorDisabled: 'rgba(0,0,0,0)',
  borderColorDisabled: '#cececf',
  cursorDisabled: 'no-drop',
  colorDark: 'white',
  backgroundColorDark: 'rgba(0,0,0,0)',
  borderColorDark: 'rgba(255,255,255,0.5)',
  boxShadowDark: 'none',
  borderColorFocusDark: '#1f91ff',
  boxShadowFocusDark: 'none',
  borderColorHoverDark: 'rgba(255,255,255,0.6)',
  borderColorErrorDark: '#e5004c',
  colorErrorDark: 'white',
  boxShadowErrorFocusDark: 'unset',
  borderColorWarningDark: '#ffc002',
  colorWarningDark: 'white',
  boxShadowWarningFocusDark: 'unset',
  colorDisabledDark: '#4d595f',
  backgroundColorDisabledDark: 'rgba(0,0,0,0)',
  borderColorDisabledDark: '#4d595f',
};
