export default {
  paddingTopGroupedFirst: '4px',
  paddingTopGrouped: '20px',
  paddingRightGrouped: '23px',
  paddingBottomGrouped: '4px',
  paddingLeftGrouped: '23px',
  paddingGrouped: '20px 23px 4px 23px',
  paddingTopGroupedFirstSm: '1px',
  paddingTopGroupedSm: '17px',
  paddingRightGroupedSm: '7px',
  paddingBottomGroupedSm: '1px',
  paddingLeftGroupedSm: '7px',
  paddingGroupedSm: '17px 7px 1px 7px',
  paddingTopGroupedFirstXs: '0px',
  paddingTopGroupedXs: '16px',
  paddingRightGroupedXs: '7px',
  paddingBottomGroupedXs: '0px',
  paddingLeftGroupedXs: '7px',
  paddingGroupedXs: '16px 7px 0px 7px',
};
