export default {
 fontSize: '16px',
 fontColor: '#323435',
 fontWeight: '400',
 height: '32px',
 borderSize: '1px',
 borderStyle: 'solid',
 borderColor: 'rgba(0,0,0,0)',
 border: '1px solid rgba(0,0,0,0)',
 borderRadius: '0',
 backgroundColor: 'white',
 marginBottom: '0',
 paddingTop: '4px',
 paddingRight: '23px',
 paddingBottom: '4px',
 paddingLeft: '23px',
 padding: '4px 23px 4px 23px',
 outline: '0',
 lineHeight: '20px',
 fontColorHover: 'black',
 backgroundColorHover: 'rgba(0,115,231,0.05)',
 fontColorSecondaryHover: '#323435',
 fontColorFocus: 'black',
 borderColorFocus: 'rgba(0,0,0,0)',
 boxShadowFocus: 'none',
 backgroundColorFocus: 'rgba(0,115,231,0.05)',
 outlineFocus: '0',
 fontColorActive: 'black',
 fontWeightActive: '600',
 backgroundColorActive: 'rgba(0,115,231,0.1)',
 fontColorSecondaryActive: '#323435',
 boxShadowColorActive: '#0073e7',
 boxShadowActive: '4px 0px 0px 0px #0073e7 inset',
 fontColorActiveEmphasized: 'white',
 backgroundColorActiveEmphasized: '#0073e7',
 fontColorDisabled: '#cececf',
 backgroundColorDisabled: 'rgba(0,0,0,0)',
 minWidthSecondary: '24px',
 fontColorSecondary: 'rgba(0,0,0,0.56)',
 marginSecondary: '0',
 paddingBottomSecondary: '3px',
 paddingTopLg: '4px',
 paddingRightLg: '31px',
 paddingBottomLg: '4px',
 paddingLeftLg: '31px',
 paddingLg: '4px 31px 4px 31px',
 heightSm: '24px',
 fontSizeSm: '16px',
 paddingTopSm: '1px',
 paddingRightSm: '7px',
 paddingBottomSm: '1px',
 paddingLeftSm: '7px',
 paddingSm: '1px 7px 1px 7px',
 heightXs: '20px',
 fontSizeXs: '12px',
 paddingTopXs: '0px',
 paddingRightXs: '7px',
 paddingBottomXs: '0px',
 paddingLeftXs: '7px',
 paddingXs: '0px 7px 0px 7px',
 paddingTopGrouped: '4px',
 paddingRightGrouped: '23px',
 paddingBottomGrouped: '4px',
 paddingLeftGrouped: '23px',
 paddingGrouped: '4px 23px 4px 23px',
 paddingTopGroupedSm: '1px',
 paddingRightGroupedSm: '7px',
 paddingBottomGroupedSm: '1px',
 paddingLeftGroupedSm: '7px',
 paddingGroupedSm: '1px 7px 1px 7px',
 paddingTopGroupedXs: '0px',
 paddingRightGroupedXs: '7px',
 paddingBottomGroupedXs: '0px',
 paddingLeftGroupedXs: '7px',
 paddingGroupedXs: '0px 7px 0px 7px',
 fontColorDark: 'rgba(255,255,255,0.8)',
 borderSizeDark: '1px',
 borderStyleDark: 'solid',
 borderColorDark: 'rgba(0,0,0,0)',
 borderDark: '1px solid rgba(0,0,0,0)',
 borderRadiusDark: '0',
 backgroundColorDark: '#203037',
 outlineDark: '0',
 fontColorHoverDark: 'white',
 backgroundColorHoverDark: 'rgba(0,115,231,0.05)',
 fontColorSecondaryHoverDark: 'rgba(255,255,255,0.8)',
 fontColorFocusDark: 'white',
 borderColorFocusDark: 'rgba(0,0,0,0)',
 boxShadowFocusDark: 'none',
 backgroundColorFocusDark: 'rgba(0,115,231,0.05)',
 outlineFocusDark: '0',
 fontColorActiveDark: 'white',
 backgroundColorActiveDark: 'rgba(0,115,231,0.2)',
 fontColorSecondaryActiveDark: 'rgba(255,255,255,0.8)',
 fontColorActiveEmphasizedDark: 'white',
 backgroundColorActiveEmphasizedDark: '#1f91ff',
 fontColorDisabledDark: '#4d595f',
 backgroundColorDisabledDark: 'rgba(0,0,0,0)',
 fontColorSecondaryDark: 'rgba(255,255,255,0.6)'
};