export default {
  order: '4',
  paddingRight: '0',
  marginTop: '-5px',
  marginRight: '-24px',
  marginBottom: '-5px',
  marginLeft: '8px',
  margin: '-5px -24px -5px 8px',
  backgroundColor: 'rgba(0,0,0,0)',
  animation: 'qtm-keyframes-list-button-container 0.41s linear',
  marginRightLg: '-32px',
  marginRightXs: '-8px',
  marginRightSm: '-8px',
  positionOverlay: 'absolute',
  bottomOverlay: '0',
  rightOverlay: '0',
  backgroundColorDark: 'rgba(0,0,0,0)',
};
