export default {
  position: 'fixed',
  display: 'flex',
  top: '56px',
  width: '100%',
  height: '48px',
  padding: '0 24px',
  justifyContent: 'space-between',
  backgroundColor: 'white',
  borderBottom: 'none',
  boxShadow: '0 7px rgba(0,0,0,0.01)',
  zIndex: '10',
  animation: 'qtm-keyframes-slideVertically 0.36s',
  backgroundColorDark: '#0d63bb',
  boxShadowDark: '0 7px rgba(0,0,0,0.01)',
};
