export default {
 height: '56px',
 fontSize: '16px',
 fontWeight: '400',
 textTransform: 'none',
 lineHeight: '16px',
 marginTop: '0',
 marginRight: '0',
 marginBottom: '0',
 marginLeft: '16px',
 margin: '0 0 0 16px',
 paddingTop: '20px',
 paddingRight: '0',
 paddingBottom: '20px',
 paddingLeft: '0',
 padding: '20px 0 20px 0',
 cursor: 'pointer',
 color: 'white',
 colorActive: 'white',
 backgroundColorActive: 'rgba(255,255,255,0.05)',
 colorHover: 'white',
 backgroundColorHover: '#0062c6',
 colorFocus: 'white',
 backgroundColorFocus: '#0062c6',
 backgroundColorPrimary: 'rgba(0,0,0,0)',
 backgroundColorPrimaryActive: 'rgba(255,255,255,0.05)',
 colorPrimaryFocus: 'white',
 backgroundColorPrimaryFocus: '#0062c6',
 backgroundColorPrimaryHover: '#0062c6',
 heightSmall: '24px',
 fontSizeSmall: '14px',
 marginLeftSmall: '16px',
 paddingTopSmall: '4px',
 paddingBottomSmall: '4px',
 colorDark: 'white',
 colorActiveDark: 'white',
 backgroundColorActiveDark: 'rgba(255,255,255,0.05)',
 colorHoverDark: 'white',
 backgroundColorHoverDark: '#0062c6'
};