export default {
  size: '14px',
  lineHeight: '16px',
  marginTop: '0',
  marginBottom: '4px',
  marginLeft: '0',
  paddingLeft: '0',
  top: '1px',
  left: '1px',
  borderColor: 'black',
  borderWidth: '2px',
  borderStyle: 'solid',
  border: '2px solid black',
  borderRadius: '100%',
  height: '10px',
  width: '10px',
  transition: 'border-color 0.1s ease-in-out',
  backgroundColor: 'rgba(0,0,0,0)',
  animationChecked:
    'qtm-keyframes-waterDrop 0.4s cubic-bezier(0.01, 0, 0.78, 0.25)',
  paddingLeftRight: '22px',
  paddingTopInline: '0',
  paddingLeftInline: '16px',
  boxShadowFocus: 'none',
  borderColorFocus: '#0073e7',
  backgroundColorFocus: 'rgba(0,0,0,0)',
  borderColorHover: 'black',
  borderColorHoverChecked: '#0073e7',
  borderHover: '2px solid black',
  borderHoverChecked: '2px solid #0073e7',
  backgroundColorHover: 'rgba(0,115,231,0.15)',
  borderColorChecked: '#0073e7',
  borderChecked: '2px solid #0073e7',
  backgroundColorChecked: 'rgba(0,0,0,0)',
  borderColorDisabled: '#cececf',
  borderDisabled: '2px solid #cececf',
  backgroundColorDisabled: 'rgba(0,0,0,0)',
  borderColorDark: '#dcdedf',
  backgroundColorDark: 'rgba(0,0,0,0)',
  animationCheckedDark:
    'qtm-keyframes-waterDrop 0.4s cubic-bezier(0.01, 0, 0.78, 0.25)',
  boxShadowFocusDark: 'none',
  borderColorFocusDark: '#1f91ff',
  backgroundColorFocusDark: 'rgba(0,0,0,0)',
  borderColorHoverDark: '#dcdedf',
  borderColorHoverCheckedDark: '#1f91ff',
  backgroundColorHoverDark: 'rgba(0,115,231,0.4)',
  borderColorCheckedDark: '#1f91ff',
  backgroundColorCheckedDark: 'rgba(0,0,0,0)',
  borderColorDisabledDark: '#4d595f',
  backgroundColorDisabledDark: 'rgba(0,0,0,0)',
};
