export default {
  size: '6px',
  style: 'solid',
  color: '#0073e7',
  borderRadius: '100%',
  top: '5px',
  left: '5px',
  paddingTop: '5px',
  paddingLeft: '5px',
  border: 'none',
  animationChecked: 'qtm-keyframes-overgrow 0.4s',
  paddingLeftRight: '12px',
  colorDisabled: '#cececf',
  colorDark: '#1f91ff',
  animationCheckedDark: 'qtm-keyframes-overgrow 0.4s',
  colorDisabledDark: '#4d595f',
};
