export default {
 zIndex: '0',
 top: '56px',
 topMastheadSecondary: '104px',
 left: '0',
 height: 'calc(100vh - 56px)',
 heightMastheadSecondary: 'calc(100vh - 104px)',
 marginTop: '0',
 marginRight: '16px',
 marginBottom: '0',
 marginLeft: '0',
 margin: '0 16px 0 0',
 boxShadow: '5px 0 rgba(50,52,53,0.05)',
 borderRight: '1px solid #dcdedf',
 paddingTop: '0',
 paddingRight: '0',
 paddingBottom: '24px',
 paddingLeft: '0',
 padding: '0 0 24px 0',
 backgroundColor: 'white',
 widthOpen: '230px',
 growthOpenHover: '8px',
 widthOpenHover: '238px',
 marginRightOpenHover: '8px',
 widthMinimized: '57px',
 growthMinimizedHover: '8px',
 widthMinimizedHover: '65px',
 marginRightMinimizedHover: '8px'
};