export default {
  height: '2px',
  borderSize: '-1px',
  borderRadius: '0',
  paddingBottom: '2px',
  top: '1px',
  borderWidth: '2px 0',
  borderColor: '#0073e7',
  backgroundColor: '#0073e7',
  border: '-1px solid #0073e7',
  borderTop: '1px solid #dcdedf',
  borderBottom: '1px solid #dcdedf',
  borderColorDark: '#1f91ff',
  backgroundColorDark: '#1f91ff',
};
