export default {
  borderLeftWidth: '4px',
  borderLeftStyle: 'solid',
  borderLeftColor: 'rgba(0,0,0,0)',
  paddingLeft: '52px',
  borderLeftColorActive: '#0073e7',
  heightXsmall: '24px',
  heightExtrasmall: '24px',
  paddingLeftXsmall: '20px',
  heightSmall: '32px',
  paddingLeftSmall: '28px',
  heightMedium: '40px',
  heightLarge: '48px',
  paddingLeftLarge: '56px',
  borderLeftColorDark: 'rgba(0,0,0,0)',
  borderLeftColorActiveDark: '#1f91ff',
};
