export default {
  height: '40px',
  fontSize: '14px',
  lineHeight: '14px',
  fontWeight: '700',
  fontStyle: 'normal',
  textTransform: 'uppercase',
  letterSpacing: '0.5px',
  borderTop: '0',
  borderRight: '0',
  borderBottom: '1px',
  borderLeft: '0',
  borderSize: '0 0 1px 0',
  borderStyle: 'solid',
  borderColor: '#dcdedf',
  paddingTop: '13px',
  paddingRight: '8px',
  paddingBottom: '12px',
  paddingLeft: '8px',
  padding: '13px 8px 12px 8px',
  color: '#323435',
  transition: '(background-color 0.12s ease-out),(color 0.12s ease-out)',
  verticalAlign: 'top',
  outlineColorFocus: '#0073e7',
  boxShadowScrolled: 'none',
  heightXsmall: '32px',
  heightExtrasmall: '32px',
  fontSizeXsmall: '16px',
  paddingTopXsmall: '8px',
  paddingRightXsmall: '4px',
  paddingBottomXsmall: '7px',
  paddingLeftXsmall: '4px',
  paddingXsmall: '8px 4px 7px 4px',
  heightSmall: '32px',
  fontSizeSmall: '16px',
  paddingTopSmall: '8px',
  paddingRightSmall: '4px',
  paddingBottomSmall: '7px',
  paddingLeftSmall: '4px',
  paddingSmall: '8px 4px 7px 4px',
  heightMedium: '32px',
  heightLarge: '40px',
  fontSizeLarge: '16px',
  paddingTopLarge: '12px',
  paddingRightLarge: '16px',
  paddingBottomLarge: '11px',
  paddingLeftLarge: '16px',
  paddingLarge: '12px 16px 11px 16px',
  borderColorDark: 'rgba(255,255,255,0.1)',
  colorDark: 'rgba(255,255,255,0.8)',
};
