export default {
 wordWrap: 'break-word',
 fontSize: '14px',
 fontFamily: 'Metric,Helvetica Neue,Helvetica,Arial,sans-serif',
 zIndex: '9999',
 backgroundColor: 'white',
 boxShadow: '2px 2px rgba(0,0,0,0.15)',
 borderRadius: '1px',
 textAlign: 'left',
 maxWidth: '200px',
 color: 'black',
 opacityVisible: '1',
 borderSize: '1px',
 borderStyle: 'solid',
 borderColor: '#dcdedf',
 border: '1px solid #dcdedf',
 padding: '5px 8px',
 borderColorDanger: '#e5004c',
 backgroundColorDanger: 'white',
 borderColorWarning: '#ffc002',
 backgroundColorWarning: 'white',
 borderColorSuccess: '#1aac60',
 backgroundColorSuccess: 'white',
 borderColorInfo: '#0073e7',
 backgroundColorInfo: 'white',
 backgroundColorDark: '#203037',
 boxShadowDark: '2px 2px rgba(0,0,0,0.3)',
 colorDark: 'white',
 borderColorDark: 'rgba(255,255,255,0.4)',
 borderColorDangerDark: '#e5004c',
 backgroundColorDangerDark: '#203037',
 borderColorWarningDark: '#ffc002',
 backgroundColorWarningDark: '#203037',
 borderColorSuccessDark: '#1aac60',
 backgroundColorSuccessDark: '#203037',
 borderColorInfoDark: '#1f91ff',
 backgroundColorInfoDark: '#203037'
};