export default {
  size: '8px',
  borderColor: '#dcdedf',
  borderWidthTop: '8px 8px 0 8px',
  borderWidthRight: '8px 8px 8px 0',
  borderWidthBottom: '0 8px 8px',
  borderWidthLeft: '8px 0 8px 8px',
  borderStyle: 'solid',
  borderColorHidden: 'rgba(0,0,0,0)',
  offset: '-2px',
  dropShadowBottomOffset: '-1px 0px -8px',
  dropShadowZIndex: '-1',
  borderColorDark: 'rgba(255,255,255,0.4)',
  borderColorHiddenDark: 'rgba(0,0,0,0)',
};
